from classifier.classifiers import NaiveBayesClassifier

words = [
    "Technology: Computer, Internet, Smartphone, Software, Hardware, Code, Algorithm, Programming, Data, Artificial Intelligence (AI), Machine Learning, Virtual Reality (VR), Augmented Reality (AR), Cybersecurity, Cloud Computing, Automation, Robotics, Blockchain, 3D Printing, Nanotechnology, Internet of Things (IoT), Big Data, Wi-Fi, Social Media, Encryption, Biotechnology, Quantum Computing, GPS (Global Positioning System), Mobile Apps, Wearable, Nanorobotics, Cryptocurrency, Data Science, Holography, Network Security, Quantum Cryptography, Silicon Valley, Drone, Information, Augmented Virtuality, Silicon Chips, Tech Startup, Internet Protocol, User Interface (UI), User Experience (UX), Data Visualization, Cyber Threats, Quantum Encryption, Tech Innovations, Machine Vision, Tech Gadgets, High-Performance Computing, Telecommunications, Firmware, Autonomous Systems, Biometric Authentication, Green, Internet Infrastructure, Semiconductor Industry, Open Source Software, SQL, Database.",

    "Science: Physics, Chemistry, Biology, Astronomy, Geology, Mathematics, Ecology, Genetics, Microbiology, Meteorology, Psychology, Neuroscience, Botany, Zoology, Environmental Science, Earth Science, Quantum Mechanics, Particle Physics, Evolution, Experiment, Hypothesis, Laboratory, Research,  Method, Data Analysis,  Theory, Biotechnology, Climate Science, Scientific Discovery, Microscope, Telescope, Ecosystem, Fossils, Chemistry,  Journal, DNA, RNA, Electromagnetism, Solar System, Geoscience, Seismology, Paleontology, Virology, Quantum Theory, Entomology, Thermodynamics, Organic Chemistry, Inorganic Chemistry, Atomic Structure,  Breakthrough, Biodiversity, Theoretical Physics, Bioinformatics,  Advancement,  Exploration, Mathematical Modeling, Biochemistry, Research Findings, Lab Equipment,  Experimentation, Ecology Conservation,  Hypothesis, Chemical Reactions,  Community, Analytical Chemistry,  Insight, Genetics Sequencing, Climate Modeling, Science Education, Observational Astronomy, Math, Mathematics, Logic, Arithmetic, Algebra, Geometry, Trigonometry, Calculus, Statistics, Probability, Linear equations, Quadratic equations,  formulas,  notation, symbols, Number theory, Complex numbers, Differential equations,  proofs,  modeling, Vector calculus,  concepts,  principles, Applied mathematics,  theorems, Number systems, Set theory,  functions,  axioms,  logic,  constants,  operations,  research, Modeling and simulation, Functions, Recursive functions, Celula, Bone, Enviroment, Earth, Planet",

    "Software Engineering: Coding, Programming, Development environment, Version control, Debugging, Algorithms, Testing, Agile, Scrum, Waterfall, DevOps, Continuous integration, Open source, User interface (UI), User experience (UX), Front-end, Back-end, Full-stack, Database, API (Application Interface), Framework, Repository, Source code, Deployment, architecture, Mobile app development, Web development, Application development, Code review, Java, Python, C, C++, C#, .Net, Lifecycle, Object-Oriented (OOP), Testing, Deployment,  Maintenance, Continuous Delivery, Scripting,  Frameworks, Database Management,  Prototyping,  Requirements,  Security,  Scalability,  Optimization, Documentation, Reliability, Performance,  Configuration,  Updates,  Integration, Code Refactoring,  Deployment Pipeline, Cross-Platform Development, as a Service (SaaS),  Development Tools, Development Life Cycle (SDLC), Mobile Application Design, Cloud Computing for Development, Microservices,  Development Paradigms, Data Analysis, Data, ETL, SQL, Server, Data Structures, Managment, Modeling and simulation, Functional, Functions, Recursive functions, SOLID, Design Patterns, F#, Haskell, Javascript, PHP, Ruby, Scala, Swift, Kotlin, Go, Rust, R, Matlab, Assembly, Shell, Perl, Delphi, Dart, Lua, Lisp, Cobol, Fortran, Visual Basic, ActionScript, Ada, Erlang, Prolog, Clojure",

    "Business: Entrepreneurship, Marketing, Management, Finance, Strategy, Investment, Startups, Leadership, Sales, Customer Service, Innovation, Profit, Competition, Market Research, Business Plan, Corporate Culture, Sustainability, Supply Chain, Networking, E-commerce, Retail, Manufacturing, Small Business, Globalization, Risk Management, Advertising, Branding, HR (Human Resources), Taxation, Business Ethics, Business Development, Market Segmentation, Business Expansion, Economic Trends, Strategic Planning, Product Development, Market Analysis, FinanciaL, Business Intelligence, Entrepreneurial Skills, Venture Capital, Consumer Behavior, Market Penetration, Business Growth, Supply Chain Management, Business Networking, B2B (Business-to-Business), Exporting, Economic Forecast, Business Innovation, Cost Analysis, Business Sustainability, Franchise Business, Intellectual Property, Business Leadership, Business Valuation, Marketing Strategies, Business Partnerships, Business Assets, Business Model, Youtube, Managment, ",

    "Art & Design: Painting, painting techniques, Sculpture, Drawing, Graphic Design, Photography, Architecture, Visual Arts, Illustration, Fine Arts, Fashion Design, Interior Design, Typography, Color Theory, Aesthetics, Creativity, Expression, Composition, Art Gallery, Mixed Media, Digital Art, Ceramics, Printmaking, Art History, Artistic Process, Museums, Fashion Trends, Conceptual Art, Product Design, User Experience (UX) Design, 3D Modeling, Abstraction, Collage, Installation, Sculptural, Textiles, Perspective, Craftsmanship, Pottery, Mosaic, Visual Communication, Decoupage, Woodworking, Artisanal, Artifacts, Ceramist, Textural, Craftsmanship, Futurism, Minimalism, Artisan, Fabrication, Artistry, Embroidery, Easel, Ephemera, Composition, Chiaroscuro, Printmaking, Craftsmanship, Surrealism.",

    "Teaching & Academics: Education, Teachers, Students, Classroom, Curriculum, Learning, School, College, University, Professor, Lecture, Research, Study, Exams, Homework, Pedagogy, Syllabus, Textbooks, Graduation, Tutoring,  Excellence, Scholarships,  Paper, Thesis, Degree, Classroom Management, Online Learning, E-Learning, Technology, Student Engagement, Pedagogical,  Achievement, Educational Resources,  Psychology,  Assessment,  Programs,  Progress, Classroom Instruction,  Research, Policy, Student Support,  Methods,  Disciplines,  Calendar,  Departments,  Accreditation,  Advising,  Development, Teaching Techniques,  Journals,  Conferences,  Philosophy,  Theory,  Standards,  Integrity, Classroom Environment,  Leadership,  Resources, Student Success, Freedom, Managment",
    
    "Personal Development: Self-improvement, Growth, Self-awareness, Goal setting, Motivation, Mindfulness, Resilience, Empowerment, Confidence, Productivity, Time management, Positive thinking, Stress management, Emotional intelligence, Self-discipline, Well-being, Health and fitness, Leadership skills, Communication, Learning, Self-care, Life skills, Adaptability, Networking,  branding, Creativity, Decision-making, Problem-solving, Financial literacy, Career development, Self-mastery, Self-reflection,  Growth, Life Balance, Inner Strength, Self-esteem,  Achievement, Habits, Mindset, Self-confidence, Work-Life Balance, Positivity, Emotional Resilience, Self-control, Wellness, Physical Fitness, Interpersonal Skills, Lifelong Learning, Self-compassion, Adaptation, Relationship Building, Image, Innovation, Critical Thinking, Financial Planning, Career Advancement, Youtube, Managment",

    "Health & Fitness: Exercise, Nutrition, Wellness, Cardiovascular, Strength training, Yoga, Meditation, Healthy eating, Weightlifting, Aerobics, Diet, Mental health, Physical activity, Bodyweight exercises, Calisthenics, Gym, Running, Swimming, Cycling, Flexibility, Hydration, Muscle mass, Rest and recovery, Weight management, Health goals, Personal trainer, Health tracking, Supplements, Well-being, Holistic health, Medicine, Fitness Regimen, Crossfit, Pilates, Functional Training, Body Composition, Endurance, Sports Nutrition, Mind-Body Connection, Balanced Diet, Strength Conditioning, HIIT (High-Intensity Interval Training), Wellness Retreat, Body Transformation, Outdoor Activities, Flexibility Training, Sports Psychology, Recovery Techniques, Mindful Eating, Holistic Healing, Physical Therapy, Lifestyle Medicine, Wellness Coaching, Biohacking, Wellness Programs, Active Lifestyle, Dietary Supplements, Energy Balance, Mental Resilience, Recovery Strategies, Integrative Health.",    
]

categories = [
    "Technology",
    "Science",
    "Software Development",
    "Business",
    "Art & Design",
    "Teaching & Academics",
    "Personal Development",
    "Health & Fitness",
]

class ClassifierFactory:
    @staticmethod
    def create_classifier():
        return NaiveBayesClassifier(words, categories)
